Update gh-pages workflow

diff --git a/.github/workflows/gh-pages.yaml b/.github/workflows/gh-pages.yaml
--- a/.github/workflows/gh-pages.yaml
+++ b/.github/workflows/gh-pages.yaml
@@ -26,12 +26,12 @@ jobs:
       - name: Build
         run: hugo --minify
 
-        - name: Check public directory exists and is not empty 
-          run: |
-            if [ ! -d "public" ] || [ -z "$(ls -A public)" ]; then
-              echo "public/ directory missing or empty. Failing workflow.";
-              exit 1;
-            fi
+      - name: Check public directory exists and is not empty
+        run: |
+          if [ ! -d "public" ] || [ -z "$(ls -A public)" ]; then
+            echo "public/ directory missing or empty. Failing workflow.";
+            exit 1;
+          fi
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
